version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    volumes:
      - ./api/:/home/docker/api/
    networks:
      main:
        aliases:
          - web
  redis:
    image: redis
    expose:
      - "6379"
    networks:
      main:
        aliases:
          - redis
  worker:
    build: celery-scheduler
    command: celery -A tasks worker -l info
    volumes:
      - ./data/:/home/docker/data/
      - ./celery-scheduler/:/home/docker/celery/
    networks:
      main:
        aliases:
          - worker
    depends_on:
      - redis
  celery-beat:
    build: celery-scheduler
    command: celery -A tasks beat -l info
    depends_on:
      - redis
    networks:
      main:
        aliases:
          - beat
networks:
  main: