version: "3"
services:
  web:
    build: 
      context: ./
      dockerfile: api/Dockerfile
    restart: always
    ports:
     - "5001:5001"
    networks:
      main:
        aliases:
          - web
  worker:
    build: 
      context: ./
      dockerfile: celery-scheduler/Dockerfile
    command: celery -A tasks worker -l info
    volumes:
      - ./data/:/home/docker/data/
    networks:
      main:
        aliases:
          - worker
    depends_on:
      - redis_celery
      - redis_leaks
  celery-beat:
    build: 
      context: ./
      dockerfile: celery-scheduler/Dockerfile
    command: celery -A tasks beat -l info
    depends_on:
      - redis_celery
      - worker
    networks:
      main:
        aliases:
          - beat
  redis_celery:
    image: redis
    expose:
      - "6379"
    networks:
      main:
        aliases:
          - redis_celery
  redis_leaks:
    image: redis
    expose:
      - "6379"
    networks:
      main:
        aliases:
          - redis_leaks
networks:
  main: